ConvertFrom-StringData @'
    Yes = Yes
    No = No
    Confirm_Message = {0} Do you want to continue?
    Confirm_YesMsg = Executing: {0}.
    Confirm_NoMsg = Skipping: {0}.
    Overwrite_Title = Confirm Overwrite
    Overwrite_Message = {0} already exists. Do you want to overwrite it?
    Overwrite_YesMsg = Overwriting {0}.
    Overwrite_NoMsg = Not overwriting {0}.
    Dism_CleanUp = Unmounting remaining Dism mounts...
    WorkDir_Title = Working Directory
    WorkDir_Message = Is the working directory {0} OK?
    WorkDir_YesMsg = Continuing with working directory {0}.
    WorkDir_NoMsg = Change the working directory.
    WorkDir_Select = Please select the working directory.
    WorkDir_NotSelected = No working directory selected, exiting.
    WorkDir_Set = Working directory set to {0}.
    Iso_Extract = Please extract the contents of the ISO to the {0} folder.
    InstallWim_NotFound = {0} file not found.
    InstallWim_ImageIndex = Please enter one ImageIndex number
    InstallWim_ImageIndex_Invalid = Invalid ImageIndex number. Please select an available index from above.
    InstallWim_Mount = Offline mount of Windows Image {0}
    InstallWim_MountedInfo = {0} Build: {1}
    InstallWim_Save = Saving the edited image
    InstallWim_Saving = Saving the edited image...
    InstallWim_Discard = Discarding the edited image.
    AppxProvisionedPackage_Remove = Removing provisioned packages
    AppxProvisionedPackage_ListFile_NotFound = RemoveAppsList.txt not found at {0}. Skipping package removal.
    AppxProvisionedPackage_Removing = Removing AppxProvisionedPackage: {0}
    AppxProvisionedPackage_Optimize = Optimizing packages...
    InboxDriver_Remove = Removing Inbox drivers
    Driver_Add = Adding drivers
    Driver_Adding = Adding drivers from {0}...
    Driver_SwitchMissing = Either -Install or -Boot switch must be specified.
    MountWindowsDir_DontOpen = Unmounting. Do not open {0}.
    ImageProcessing_Error = An error occurred during image processing: {0}
    ISOFile_Create = Creating an ISO file
    ISOFile_VolumeLabel = Enter the ISO Volume Label
    ISOFile_FileName = Enter the ISO File Name
    OSCDImg_NotFound = oscdimg.exe not found at {0}. Aborting ISO creation.
'@
