ConvertFrom-StringData @'
    Yes = はい(&Yes)
    No = いいえ(&No)
    Confirm_Message = {0} 続行しますか？
    Confirm_YesMsg = {0} を実行します。
    Confirm_NoMsg = {0} をスキップします。
    Overwrite_Title = 上書き確認
    Overwrite_Message = {0} は既に存在します。上書きしますか？
    Overwrite_YesMsg = {0} を上書きします。
    Overwrite_NoMsg = {0} を上書きしません。
    Dism_CleanUp = 残っているDismのマウントをアンマウントしています...
    WorkDir_Title = 作業ディレクトリ
    WorkDir_Message = 作業ディレクトリの場所は {0} でよろしいですか？
    WorkDir_YesMsg = 作業ディレクトリの場所 {0} で続行します。
    WorkDir_NoMsg = 作業ディレクトリの場所を変更します。
    WorkDir_Select = 作業ディレクトリを選択してください。
    WorkDir_NotSelected = 作業ディレクトリが選択されていないため終了します。
    WorkDir_Set = 作業ディレクトリを {0} に設定しました。
    Iso_Extract = {0} フォルダに、isoファイルの中身を展開してください。
    InstallWim_NotFound = {0} ファイルが見つかりません。
    InstallWim_ImageIndex = ImageIndex 番号を1つ入力してください。
    InstallWim_ImageIndex_Invalid = 無効な ImageIndex 番号です。利用可能なインデックスを上記から選択してください。
    InstallWim_Mount = Windowsイメージ {0} のオフラインマウント
    InstallWim_MountedInfo = {0} Build: {1}
    InstallWim_Save = 編集したイメージの保存
    InstallWim_Saving = 編集したイメージを保存中...
    InstallWim_Discard = 編集したイメージを破棄します。
    AppxProvisionedPackage_Remove = プロビジョニングパッケージの削除
    AppxProvisionedPackage_ListFile_NotFound = RemoveAppsList.txt が {0} に見つかりません。パッケージの削除をスキップします。
    AppxProvisionedPackage_Removing = プロビジョニングパッケージを削除中: {0}
    AppxProvisionedPackage_Optimize = パッケージの最適化中...
    InboxDriver_Remove = インボックスドライバーの削除
    MountWindowsDir_DontOpen = アンマウントします。 {0} を開かないでください。
    ImageProcessing_Error = イメージ処理中にエラーが発生しました: {0}
    ISOFile_Create = ISOファイルの作成
    ISOFile_VolumeLabel = ISOボリュームラベルを入力してください
    ISOFile_FileName = ISOファイル名を入力してください
'@
